org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.21.1
neo_version=21.1.72
neo_version_range=[21.1.0,)
loader_version_range=[4,)
parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.17

mod_id=smmorpg
mod_name=SmmoRPG - Ultra Realistic Combat
mod_license=GPL-3.0-only
mod_version=1.0.0
mod_group_id=com.smmorpg
mod_authors=AhmetYasir61
mod_description=Ultra realistic FPS/TPS combat, Sekiro-style classes, level & loot, holy/cursed affixes, locational wounds, bleeding and 60 impact sounds.
